	BASERUBY = /usr/bin/ruby --disable=gems
	CC = gcc
	LD = ld
	LDSHARED = gcc -shared
	CFLAGS = -O2 -pipe -mcpu=powerpc -mtune=750 -msecure-plt -mno-altivec -fPIC 
	XCFLAGS = -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fno-strict-overflow -fvisibility=hidden -fexcess-precision=standard -DRUBY_EXPORT -DCANONICALIZATION_FOR_MATHN -I. -I.ext/include/powerpc-linux -I./include -I. -I./enc/unicode/12.1.0
	CPPFLAGS =   
	DLDFLAGS = -Wl,--compress-debug-sections=zlib -Wl,-soname,libruby.so.2.7  -fstack-protector-strong  
	SOLIBS = -lz -lpthread -lrt -lrt -lgmp -ldl -lcrypt -lm 
	LANG = 
	LC_ALL = 
	LC_CTYPE = 
	MFLAGS = 
gcc (CRUX-PPC) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

./revision.h unchanged
generating enc.mk
making srcs under enc
make[1]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2'
make[1]: Nothing to be done for 'srcs'.
make[1]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2'
generating transdb.h
transdb.h unchanged
generating makefiles ext/configure-ext.mk
ext/configure-ext.mk updated
make[1]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2'
make[1]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2'
generating makefile exts.mk
exts.mk unchanged
make[1]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2'
make[2]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/bigdecimal'
make[2]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/bigdecimal'
make[2]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/rubyvm'
make[2]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/rubyvm'
make[2]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/pty'
make[2]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/pty'
make[2]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/digest'
make[2]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/digest'
make[2]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/digest/sha2'
make[2]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/digest/sha2'
make[2]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/ripper'
make[2]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/ripper'
make[2]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/pathname'
make[2]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/pathname'
make[2]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/monitor'
make[2]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/monitor'
make[2]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/psych'
make[2]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/psych'
make[2]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/openssl'
make[2]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/openssl'
make[2]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/json'
make[2]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/json'
make[2]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/socket'
make[2]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/socket'
make[2]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/io/console'
make[2]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/io/console'
make[2]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/fiddle'
make[2]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/fiddle'
make[2]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/date'
make[2]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/date'
make[2]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/nkf'
make[2]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/nkf'
make[2]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/syslog'
make[2]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/syslog'
make[2]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/coverage'
make[2]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2/ext/coverage'
make[2]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2'
./revision.h unchanged
make[2]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2'
make[1]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2'
make[1]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2'
make[1]: Nothing to be done for 'note'.
make[1]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2'
making enc
make[1]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2'
make[1]: Nothing to be done for 'enc'.
make[1]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2'
making trans
make[1]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2'
make[1]: Nothing to be done for './enc/trans'.
make[1]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2'
making encs
make[1]: Entering directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2'
make[1]: Nothing to be done for 'encs'.
make[1]: Leaving directory '/usr/ports/opt/ruby/work/src/ruby-2.7.2'
test_attr.rb             ..
test_autoload.rb         ........
test_block.rb            ..........................................................
test_class.rb            ................................................
test_env.rb              ..
test_eval.rb             .....................................
test_exception.rb        ..................................
test_fiber.rb            .....
test_finalizer.rb        .
test_flip.rb             .
test_flow.rb             ..............................................................
test_fork.rb             ....
test_gc.rb               ..
test_insns.rb            ........................................................................................................................................................................................................................................................................................................................................................................................................
test_io.rb               .........
test_jump.rb             .............................
test_literal.rb          ............................................................................................................................................................
test_literal_suffix.rb   ................................................
test_load.rb             ..
test_marshal.rb          .
test_massign.rb          ..................................
test_method.rb           ...............................................................................................................................................................................................................................
test_objectspace.rb      ......
test_proc.rb             .......................................
test_string.rb           .
test_struct.rb           .
test_syntax.rb           ............................................................................................................................................................
test_thread.rb           ................................................
Fiber count: 9366 (can't alloc machine stack to fiber (1 x 331776 bytes): Cannot allocate memory)
PASS all 1409 tests
exec ./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems "./bootstraptest/runner.rb" --ruby="ruby --disable-gems"   ./KNOWNBUGS.rb
2020-11-13 21:27:37 +0000
Driver is ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [powerpc-linux]
Target is ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [powerpc-linux]

KNOWNBUGS.rb   
No tests, no problem
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:assignment ....................................................................................................................................................................................................................................................................................................................................................................................OK 372
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:condition ..OK 2
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:if/unless ...OK 3
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:case .....OK 5
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:while/until ........OK 8
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:exception ..........OK 10
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:array .......................................OK 39
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:hash ...........................OK 27
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:iterator .............................................................................................................OK 109
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:float ................................................................................OK 80
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:bignum ...............................OK 31
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:string & char ..............................................................OK 62
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:assignment ..........OK 10
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:call ......OK 6
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:proc .........OK 9
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:signal ..OK 2
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:eval ...........................OK 27
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:system ........OK 8
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:const .....OK 5
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:clone .....OK 5
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:marshal ....OK 4
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:pack ....OK 4
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:math ..OK 2
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:struct ......OK 6
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:variable ...........OK 11
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:trace ...OK 3
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:defined? ............OK 12
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:alias ......OK 6
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:path .......................OK 23
/usr/ports/opt/ruby/work/src/ruby-2.7.2/basictest/test.rb:gc ....OK 4

test succeeded
Run options: "--ruby=./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems"

# Running tests:

Finished tests in 22.719235s, 10.0796 tests/s, 22.0078 assertions/s.
229 tests, 500 assertions, 0 failures, 0 errors, 0 skips

ruby -v: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [powerpc-linux]
config.status: creating ruby-runner.h
making mjit_build_dir.so
Gem::Indexer tests are being skipped.  Install builder gem.
generate_index tests are being skipped.  Install builder gem.
Run options: "--ruby=./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems" --excludes-dir=./test/excludes --name=!/memory_leak/

# Running tests:

Environment variable changed: Reline::Config::Test#test_relative_xdg_config_home : "HOME" changed : "/root" -> "/tmp/test_reline_config_4600"
Environment variable changed: Reline::Config::Test#test_relative_xdg_config_home : "XDG_CONFIG_HOME" added
/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_fiber.rb:318:in `transfer': can't alloc machine stack to fiber (1 x 331776 bytes): Cannot allocate memory (FiberError)
	from /usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_fiber.rb:318:in `block (6 levels) in test_fork_from_fiber'
	from /usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_fiber.rb:317:in `times'
	from /usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_fiber.rb:317:in `block (5 levels) in test_fork_from_fiber'
	from /usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_fiber.rb:313:in `fork'
	from /usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_fiber.rb:313:in `block (4 levels) in test_fork_from_fiber'

/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:606: warning: 'opt_invokebuiltin_delegate_leave' insn is not included in the script. Actual insns are: opt_invokebuiltin_delegate leave
/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:936: warning: /usr/bin/ld: /tmp/_ruby_mjit_p16858u0.o: in function `_mjit0':
_ruby_mjit_p16858u0.c:(.text+0x758): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p16858u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status

  1) Failure:
Reline::Config::Test#test_empty_xdg_config_home [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/reline/test_config.rb:298]:
<"/tmp/test_reline_config_4600/.config/readline/inputrc"> expected but was
<"/etc/inputrc">.

  2) Failure:
Reline::Config::Test#test_relative_xdg_config_home [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/reline/test_config.rb:320]:
<"/tmp/test_reline_config_4600/.config/readline/inputrc"> expected but was
<"/etc/inputrc">.

  3) Failure:
Reline::Config::Test#test_xdg_config_home [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/reline/test_config.rb:283]:
<"/tmp/test_reline_config_4600/.config/example_dir/readline/inputrc"> expected but was
<"/etc/inputrc">.

  4) Failure:
TestFiber#test_fork_from_fiber [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_fiber.rb:330]:
[ruby-core:41456].
<0> expected but was
<1>.

  5) Failure:
TestFileExhaustive#test_expand_path_for_existent_username [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_file_exhaustive.rb:1098]:
<"/tmp/test_reline_config_4600"> expected but was
<"/root">.

  6) Failure:
TestIRB::TestInit#test_rc_file [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/irb/test_init.rb:29]:
<"/tmp/test_irb_init_460020201113-4600-16jr9z5/.irbrc"> expected but was
<".config/example_dir/irb/irbrc">.

  7) Failure:
TestIRB::TestInit#test_rc_file_in_subdir [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/irb/test_init.rb:50]:
<"/tmp/test_irb_init_460020201113-4600-1wgz9pj/.irbrc"> expected but was
<".config/example_dir/irb/irbrc">.

  8) Failure:
TestJIT#test_attr_reader [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:812]:
Expected 2 times of JIT success, but succeeded 0 times.

script:
"""

class A
  attr_reader :a, :b

  def initialize
    @a = 2
  end

  def test
    a
  end

  def undefined
    b
  end
end

a = A.new
print(a.test * a.test)
p(a.undefined)
p(a.undefined)

# redefinition
def a.test
  3
end

print(2 * a.test)

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p9165u0.o: in function `_mjit0':
_ruby_mjit_p9165u0.c:(.text+0x46c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p9165u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p9165u1.o: in function `_mjit1':
_ruby_mjit_p9165u1.c:(.text+0x46c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p9165u1.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<2> expected but was
<0>.

  9) Failure:
TestJIT#test_block_handler_with_possible_frame_omitted_inlining [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:952]:
Expected 2 times of JIT success, but succeeded 1 times.

script:
"""

def multiply(a, b)
  a *= b
end

3.times do
  p multiply(7.0, 10.0)
end

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p9344u0.o: in function `_mjit0':
_ruby_mjit_p9344u0.c:(.text+0x798): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p9344u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
JIT success (303.2ms): multiply@-e:2 -> /tmp/_ruby_mjit_p9344u1.c
Successful MJIT finish

"""

.
<2> expected but was
<1>.

 10) Failure:
TestJIT#test_catching_deep_exception [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:748]:
Expected 4 times of JIT success, but succeeded 1 times.

script:
"""

def catch_true(paths, prefixes) # catch_except_p: TRUE
  prefixes.each do |prefix| # catch_except_p: TRUE
    paths.each do |path| # catch_except_p: FALSE
      return path
    end
  end
end

def wrapper(paths, prefixes)
  catch_true(paths, prefixes)
end

print wrapper(['1'], ['2'])

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p9743u0.o: in function `_mjit0':
_ruby_mjit_p9743u0.c:(.text+0x49c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p9743u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p9743u1.o: in function `method_missing.constprop.16':
_ruby_mjit_p9743u1.c:(.text+0x344): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p9743u1.o: in function `refine_sym_proc_call':
_ruby_mjit_p9743u1.c:(.text+0x69c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p9743u1.o: in function `_mjit1':
_ruby_mjit_p9743u1.c:(.text+0xe7c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p9743u1.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p9743u2.o: in function `method_missing.constprop.16':
_ruby_mjit_p9743u2.c:(.text+0x344): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p9743u2.o: in function `refine_sym_proc_call':
_ruby_mjit_p9743u2.c:(.text+0x69c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p9743u2.o: in function `_mjit2':
_ruby_mjit_p9743u2.c:(.text+0xeb0): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p9743u2.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
JIT success (513.7ms): block (2 levels) in catch_true@-e:4 -> /tmp/_ruby_mjit_p9743u3.c
Successful MJIT finish

"""

.
<4> expected but was
<1>.

 11) Failure:
TestJIT#test_compile_insn_adjuststack [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:329]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc {  
  x = [true]
  x[0] ||= nil
  x[0]
}.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p10990u0.o: in function `_mjit0':
_ruby_mjit_p10990u0.c:(.text+0x578): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p10990u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 12) Failure:
TestJIT#test_compile_insn_blockparam [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:87]:
Expected 2 times of JIT success, but succeeded 1 times.

script:
"""

def foo(&b)
  a = b
  b = 2
  a.call + 2
end

print foo { 1 }

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p11052u0.o: in function `_mjit0':
_ruby_mjit_p11052u0.c:(.text+0x644): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p11052u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
JIT success (314.2ms): block in <main>@-e:8 -> /tmp/_ruby_mjit_p11052u1.c
Successful MJIT finish

"""

.
<2> expected but was
<1>.

 13) Failure:
TestJIT#test_compile_insn_checkkeyword [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:342]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""

def test(x: rand)
  x
end
print test(x: true)

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p11379u0.o: in function `_mjit0':
_ruby_mjit_p11379u0.c:(.text+0x5ac): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p11379u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 14) Failure:
TestJIT#test_compile_insn_checkmatch_opt_case_dispatch [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:499]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc {  
  case 'hello'
  when 'hello'
    'world'
  end
}.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p11483u0.o: in function `_mjit0':
_ruby_mjit_p11483u0.c:(.text+0x344): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p11483u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 15) Failure:
TestJIT#test_compile_insn_checktype [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:483]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc {  
  a = '2'
  "4#{a}"
}.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p11566u0.o: in function `_mjit0':
_ruby_mjit_p11566u0.c:(.text+0x618): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p11566u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 16) Failure:
TestJIT#test_compile_insn_concatarray [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:268]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc { ["t", "r", *x = "u", "e"].join }.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p11802u0.o: in function `_mjit0':
_ruby_mjit_p11802u0.c:(.text+0x6d4): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p11802u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 17) Failure:
TestJIT#test_compile_insn_constant [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:167]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc {  
  FOO = 1
  FOO
}.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p11844u0.o: in function `_mjit0':
_ruby_mjit_p11844u0.c:(.text+0x88c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p11844u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 18) Failure:
TestJIT#test_compile_insn_defined [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:338]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc { defined?(a) }.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p11934u0.o: in function `_mjit0':
_ruby_mjit_p11934u0.c:(.text+0x1e8): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p11934u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 19) Failure:
TestJIT#test_compile_insn_definemethod_definesmethod [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:200]:
Expected 3 times of JIT success, but succeeded 2 times.

script:
"""

print 1.times.map {
  def method_definition
    'hello'
  end

  def self.smethod_definition
    'world'
  end

  method_definition + smethod_definition
}.join

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p11988u0.o: in function `vm_sendish.constprop.13':
_ruby_mjit_p11988u0.c:(.text+0x3f0): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p11988u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
JIT success (387.1ms): method_definition@-e:3 -> /tmp/_ruby_mjit_p11988u1.c
JIT success (414.5ms): smethod_definition@-e:7 -> /tmp/_ruby_mjit_p11988u2.c
Successful MJIT finish

"""

.
<3> expected but was
<2>.

 20) Failure:
TestJIT#test_compile_insn_dupn [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:305]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc {  
  klass = Class.new
  klass::X ||= true
}.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p12233u0.o: in function `_mjit0':
_ruby_mjit_p12233u0.c:(.text+0xfa4): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p12233u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 21) Failure:
TestJIT#test_compile_insn_expandarray [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:264]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc { y = [ true, false, nil ]; x, = y; x }.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p12307u0.o: in function `_mjit0':
_ruby_mjit_p12307u0.c:(.text+0x274): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p12307u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 22) Failure:
TestJIT#test_compile_insn_freezestring [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:236]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""

# frozen_string_literal: true
print proc { "#{true}".frozen? }.call

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p12382u0.o: in function `vm_sendish.constprop.5':
_ruby_mjit_p12382u0.c:(.text+0x3f0): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p12382u0.o: in function `_mjit0':
_ruby_mjit_p12382u0.c:(.text+0x5f4): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p12382u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 23) Failure:
TestJIT#test_compile_insn_getblockparamproxy [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:100]:
Expected 3 times of JIT success, but succeeded 1 times.

script:
"""

def bar(&b)
  b.call
end

def foo(&b)
  bar(&b) * bar(&b)
end

print foo { 2 }

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p12433u0.o: in function `vm_sendish.constprop.18':
_ruby_mjit_p12433u0.c:(.text+0xa0c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p12433u0.o: in function `method_missing.constprop.19':
_ruby_mjit_p12433u0.c:(.text+0xd20): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p12433u0.o: in function `refine_sym_proc_call':
_ruby_mjit_p12433u0.c:(.text+0x1078): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p12433u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p12433u1.o: in function `_mjit1':
_ruby_mjit_p12433u1.c:(.text+0x558): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p12433u1.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
JIT success (191.1ms): block in <main>@-e:10 -> /tmp/_ruby_mjit_p12433u2.c
Successful MJIT finish

"""

.
<3> expected but was
<1>.

 24) Failure:
TestJIT#test_compile_insn_inlinecache [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:491]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc { Struct }.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p12719u0.o: in function `_mjit0':
_ruby_mjit_p12719u0.c:(.text+0x6b8): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p12719u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 25) Failure:
TestJIT#test_compile_insn_instancevariable [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:126]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc {  
  @foo = 1
  @foo
}.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p12792u0.o: in function `_mjit0':
_ruby_mjit_p12792u0.c:(.text+0x468): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p12792u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 26) Failure:
TestJIT#test_compile_insn_intern_duparray [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:260]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc { [:"#{0}"] + [1,2,3] }.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p12804u0.o: in function `_mjit0':
_ruby_mjit_p12804u0.c:(.text+0x620): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p12804u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 27) Failure:
TestJIT#test_compile_insn_invokeblock_leave [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:428]:
Expected 2 times of JIT success, but succeeded 1 times.

script:
"""

def foo
  yield
end
print foo { 2 }

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p12902u0.o: in function `rb_warn_check.part.13':
_ruby_mjit_p12902u0.c:(.text+0x2c0): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p12902u0.o: in function `args_pop_keyword_hash':
_ruby_mjit_p12902u0.c:(.text+0xef8): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p12902u0.o: in function `setup_parameters_complex':
_ruby_mjit_p12902u0.c:(.text+0x222c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p12902u0.o: in function `_mjit0':
_ruby_mjit_p12902u0.c:(.text+0x3814): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p12902u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
JIT success (420.7ms): block in <main>@-e:5 -> /tmp/_ruby_mjit_p12902u1.c
Successful MJIT finish

"""

.
<2> expected but was
<1>.

 28) Failure:
TestJIT#test_compile_insn_invokesuper [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:410]:
Expected 4 times of JIT success, but succeeded 2 times.

script:
"""

mod = Module.new {
  def test
    super + 2
  end
}
klass = Class.new {
  prepend mod
  def test
    1
  end
}
print klass.new.test

"""


stderr:
"""
JIT success (485.4ms): block in <main>@-e:2 -> /tmp/_ruby_mjit_p13044u0.c
/usr/bin/ld: /tmp/_ruby_mjit_p13044u1.o: in function `_mjit1':
_ruby_mjit_p13044u1.c:(.text+0x7a8): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p13044u1.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p13044u2.o: in function `vm_call_ivar':
_ruby_mjit_p13044u2.c:(.text+0x414): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p13044u2.o: in function `rb_warn_check.part.48':
_ruby_mjit_p13044u2.c:(.text+0x5f8): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p13044u2.o: in function `vm_call_attrset':
_ruby_mjit_p13044u2.c:(.text+0xc8c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p13044u2.o: in function `args_pop_keyword_hash':
_ruby_mjit_p13044u2.c:(.text+0xf44): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p13044u2.o: in function `method_missing.constprop.68':
_ruby_mjit_p13044u2.c:(.text+0x258c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p13044u2.o:_ruby_mjit_p13044u2.c:(.text+0x2b38): more undefined references to `__stack_chk_fail_local' follow
/usr/bin/ld: /tmp/_ruby_mjit_p13044u2.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
JIT success (334.7ms): test@-e:9 -> /tmp/_ruby_mjit_p13044u3.c
Successful MJIT finish

"""

.
<4> expected but was
<2>.

 29) Failure:
TestJIT#test_compile_insn_local [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:69]:
Expected 3 times of JIT success, but succeeded 1 times.

script:
"""

def foo
  a = 0
  [1, 2].each do |i|
    a += i
    [3, 4].each do |j|
      a *= j
    end
  end
  a
end

print foo

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p13456u0.o: in function `method_missing.constprop.16':
_ruby_mjit_p13456u0.c:(.text+0x3a0): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p13456u0.o: in function `refine_sym_proc_call':
_ruby_mjit_p13456u0.c:(.text+0x6f8): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p13456u0.o: in function `_mjit0':
_ruby_mjit_p13456u0.c:(.text+0xf14): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p13456u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p13456u1.o: in function `method_missing.constprop.17':
_ruby_mjit_p13456u1.c:(.text+0x3a8): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p13456u1.o: in function `refine_sym_proc_call':
_ruby_mjit_p13456u1.c:(.text+0x700): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p13456u1.o: in function `_mjit1':
_ruby_mjit_p13456u1.c:(.text+0x1048): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p13456u1.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
JIT success (614.9ms): block (2 levels) in foo@-e:6 -> /tmp/_ruby_mjit_p13456u2.c
Successful MJIT finish

"""

.
<3> expected but was
<1>.

 30) Failure:
TestJIT#test_compile_insn_newarray [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:248]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc {  
  a, b, c = 1, 2, 3
  [a, b, c]
}.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p13550u0.o: in function `_mjit0':
_ruby_mjit_p13550u0.c:(.text+0x1e8): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p13550u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 31) Failure:
TestJIT#test_compile_insn_newarraykwsplat [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:256]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc { [**{ x: 1 }] }.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p13575u0.o: in function `_mjit0':
_ruby_mjit_p13575u0.c:(.text+0x524): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p13575u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 32) Failure:
TestJIT#test_compile_insn_newhash [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:276]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc { a = 1; { a: a } }.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p13632u0.o: in function `_mjit0':
_ruby_mjit_p13632u0.c:(.text+0x1ac): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p13632u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 33) Failure:
TestJIT#test_compile_insn_once [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:495]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc { /#{true}/o =~ "true" && $~.to_a }.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p13803u0.o: in function `_mjit0':
_ruby_mjit_p13803u0.c:(.text+0x870): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p13803u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 34) Failure:
TestJIT#test_compile_insn_opt_aref [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:549]:
Expected 2 times of JIT success, but succeeded 1 times.

script:
"""

obj = Object.new
def obj.[](h)
  h
end

block = proc { |h| h[1] }
print block.call(obj)
print block.call({ 1 => 2 })
print block.call({ 1 => 2 })

"""


stderr:
"""
JIT success (352.3ms): block in <main>@-e:7 -> /tmp/_ruby_mjit_p13972u0.c
JIT recompile: block in <main>@-e:7
/usr/bin/ld: /tmp/_ruby_mjit_p13972u1.o: in function `_mjit1':
_ruby_mjit_p13972u1.c:(.text+0x484): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p13972u1.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<2> expected but was
<1>.

 35) Failure:
TestJIT#test_compile_insn_opt_aset [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:568]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc {  
  hash = { '1' => 2 }
  (hash['2'] = 2) + (hash[1.to_s] = 3)
}.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p14130u0.o: in function `_mjit0':
_ruby_mjit_p14130u0.c:(.text+0x724): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p14130u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 36) Failure:
TestJIT#test_compile_insn_opt_empty_p [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:584]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc { [].empty? }.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p14427u0.o: in function `_mjit0':
_ruby_mjit_p14427u0.c:(.text+0x1fc): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p14427u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 37) Failure:
TestJIT#test_compile_insn_opt_newarray_max [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:388]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc {  
  a = 1
  b = 2
  [a, b].max
}.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p14670u0.o: in function `_mjit0':
_ruby_mjit_p14670u0.c:(.text+0x3f0): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p14670u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 38) Failure:
TestJIT#test_compile_insn_opt_newarray_min [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:397]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc {  
  a = 1
  b = 2
  [a, b].min
}.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p14758u0.o: in function `_mjit0':
_ruby_mjit_p14758u0.c:(.text+0x3d8): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p14758u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 39) Failure:
TestJIT#test_compile_insn_opt_send_without_block [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:406]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc { print }.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p15179u0.o: in function `_mjit0':
_ruby_mjit_p15179u0.c:(.text+0x46c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p15179u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 40) Failure:
TestJIT#test_compile_insn_putself [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:187]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""

proc { print "hello" }.call

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p15747u0.o: in function `_mjit0':
_ruby_mjit_p15747u0.c:(.text+0x490): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p15747u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 41) Failure:
TestJIT#test_compile_insn_putspecialobject [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:217]:
Expected 2 times of JIT success, but succeeded 1 times.

script:
"""

print 1.times.map {
  def a
    'a'
  end

  alias :b :a

  b
}.join

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p15784u0.o: in function `vm_sendish.constprop.13':
_ruby_mjit_p15784u0.c:(.text+0x3f0): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p15784u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
JIT success (308.7ms): a@-e:3 -> /tmp/_ruby_mjit_p15784u1.c
Successful MJIT finish

"""

.
<2> expected but was
<1>.

 42) Failure:
TestJIT#test_compile_insn_putstring_concatstrings_tostring [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:232]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc { "a#{}b" + "c" }.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p15875u0.o: in function `_mjit0':
_ruby_mjit_p15875u0.c:(.text+0x654): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p15875u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 43) Failure:
TestJIT#test_compile_insn_reverse [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:317]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc { q, (w, e), r = 1, [2, 3], 4; [q, w, e, r] }.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p15911u0.o: in function `_mjit0':
_ruby_mjit_p15911u0.c:(.text+0x34c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p15911u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 44) Failure:
TestJIT#test_compile_insn_send [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:360]:
Expected 2 times of JIT success, but succeeded 1 times.

script:
"""

print proc { yield_self { 1 } }.call

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p15998u0.o: in function `method_missing.constprop.16':
_ruby_mjit_p15998u0.c:(.text+0x344): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p15998u0.o: in function `refine_sym_proc_call':
_ruby_mjit_p15998u0.c:(.text+0x69c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p15998u0.o: in function `_mjit0':
_ruby_mjit_p15998u0.c:(.text+0xe90): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p15998u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
JIT success (306.0ms): block (2 levels) in <main>@-e:2 -> /tmp/_ruby_mjit_p15998u1.c
Successful MJIT finish

"""

.
<2> expected but was
<1>.

 45) Failure:
TestJIT#test_compile_insn_splatarray [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:272]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc { [*(1..2)] }.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p16234u0.o: in function `_mjit0':
_ruby_mjit_p16234u0.c:(.text+0x130): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p16234u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 46) Failure:
TestJIT#test_compile_insn_throw [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:438]:
Expected 2 times of JIT success, but succeeded 1 times.

script:
"""

def test
  proc do
    if 1+1 == 1
      return 3
    else
      return 4
    end
    5
  end.call
end
print test

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p16427u0.o: in function `vm_sendish.constprop.16':
_ruby_mjit_p16427u0.c:(.text+0x5cc): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p16427u0.o: in function `method_missing.constprop.17':
_ruby_mjit_p16427u0.c:(.text+0x8e0): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p16427u0.o: in function `refine_sym_proc_call':
_ruby_mjit_p16427u0.c:(.text+0xc38): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p16427u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
JIT success (649.5ms): block in test@-e:3 -> /tmp/_ruby_mjit_p16427u1.c
Successful MJIT finish

"""

.
<2> expected but was
<1>.

 47) Failure:
TestJIT#test_compile_insn_toregexp [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:244]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""
p proc { /#{true}/ =~ "true" }.call
"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p16487u0.o: in function `_mjit0':
_ruby_mjit_p16487u0.c:(.text+0x654): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p16487u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 48) Failure:
TestJIT#test_inlined_setivar_frozen [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:790]:
Expected 2 times of JIT success, but succeeded 1 times.

script:
"""

class A
  def a
    @a = 1
  end
end

a = A.new
a.a
a.a
a.a
a.freeze
begin
  a.a
rescue FrozenError => e
  p e.class
end

"""


stderr:
"""
JIT success (373.3ms): a@-e:3 -> /tmp/_ruby_mjit_p17000u0.c
JIT recompile: a@-e:3
/usr/bin/ld: /tmp/_ruby_mjit_p17000u1.o: in function `_mjit1':
_ruby_mjit_p17000u1.c:(.text+0x234): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17000u1.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<2> expected but was
<1>.

 49) Failure:
TestJIT#test_inlined_undefined_ivar [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:767]:
Expected 3 times of JIT success, but succeeded 1 times.

script:
"""

class Foo
  def initialize
    @a = :a
  end

  def bar
    if @b.nil?
      @b = :b
    end
  end
end

verbose, $VERBOSE = $VERBOSE, false # suppress "instance variable @b not initialized"
print(Foo.new.bar)
print(Foo.new.bar)
print(Foo.new.bar)
$VERBOSE = verbose

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p17126u0.o: in function `_mjit0':
_ruby_mjit_p17126u0.c:(.text+0x244): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17126u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
JIT success (433.7ms): bar@-e:7 -> /tmp/_ruby_mjit_p17126u1.c
JIT recompile: bar@-e:7
/usr/bin/ld: /tmp/_ruby_mjit_p17126u2.o: in function `_mjit2':
_ruby_mjit_p17126u2.c:(.text+0x748): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17126u2.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<3> expected but was
<1>.

 50) Failure:
TestJIT#test_jit_output [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:613]:
Expected /^JIT success \(\d+\.\dms\): block in <main>@-e:1 -> .+_ruby_mjit_p\d+u\d+\.c$/ to match "/usr/bin/ld: /tmp/_ruby_mjit_p17182u0.o: in function `_mjit0':\n" +
"_ruby_mjit_p17182u0.c:(.text+0x490): undefined reference to `__stack_chk_fail_local'\n" +
"/usr/bin/ld: /tmp/_ruby_mjit_p17182u0.so: hidden symbol `__stack_chk_fail_local' isn't defined\n" +
"/usr/bin/ld: final link failed: bad value\n" +
"collect2: error: ld returned 1 exit status\n" +
"Successful MJIT finish\n".

 51) Failure:
TestJIT#test_jump_to_precompiled_branch [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:876]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""

def test(foo)
  ".#{foo unless foo == 1}" if true
end
print test(0)

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p17255u0.o: in function `_mjit0':
_ruby_mjit_p17255u0.c:(.text+0x810): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17255u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 52) Failure:
TestJIT#test_lambda_longjmp [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:915]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""

fib = lambda do |x|
  return x if x == 0 || x == 1
  fib.call(x-1) + fib.call(x-2)
end
print fib.call(5)

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p17296u0.o: in function `vm_sendish.constprop.17':
_ruby_mjit_p17296u0.c:(.text+0x3cc): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17296u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 53) Failure:
TestJIT#test_local_stack_on_exception [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:708]:
Expected 2 times of JIT success, but succeeded 0 times.

script:
"""

def b
  raise
rescue
  2
end

def a
  # Calling #b should be vm_exec, not direct mjit_exec.
  # Otherwise `1` on local variable would be purged.
  1 + b
end

print a

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p17385u0.o: in function `_mjit0':
_ruby_mjit_p17385u0.c:(.text+0x4cc): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17385u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p17385u1.o: in function `_mjit1':
_ruby_mjit_p17385u1.c:(.text+0x47c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17385u1.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<2> expected but was
<0>.

 54) Failure:
TestJIT#test_local_stack_with_sp_motion_by_blockargs [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:727]:
Expected 2 times of JIT success, but succeeded 1 times.

script:
"""

def b(base)
  1
end

# This method is simple enough to have false in catch_except_p.
# So local_stack_p would be true in JIT compiler.
def a
  m = method(:b)

  # ci->flag has VM_CALL_ARGS_BLOCKARG and cfp->sp is moved in vm_caller_setup_arg_block.
  # So, for this send insn, JIT-ed code should use cfp->sp instead of local variables for stack.
  Module.module_eval(&m)
end

print a

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p17431u0.o: in function `vm_sendish.constprop.22':
_ruby_mjit_p17431u0.c:(.text+0x630): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17431u0.o: in function `method_missing.constprop.23':
_ruby_mjit_p17431u0.c:(.text+0x944): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17431u0.o: in function `refine_sym_proc_call':
_ruby_mjit_p17431u0.c:(.text+0xc9c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17431u0.o: in function `_mjit0':
_ruby_mjit_p17431u0.c:(.text+0x178c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17431u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
JIT success (198.1ms): b@-e:2 -> /tmp/_ruby_mjit_p17431u1.c
Successful MJIT finish

"""

.
<2> expected but was
<1>.

 55) Failure:
TestJIT#test_nothing_to_unload_with_jit_wait [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:618]:
Expected 11 times of JIT success, but succeeded 0 times.

script:
"""

def a1() a2() end
def a2() a3() end
def a3() a4() end
def a4() a5() end
def a5() a6() end
def a6() a7() end
def a7() a8() end
def a8() a9() end
def a9() a10() end
def a10() a11() end
def a11() print('hello') end
a1

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p17511u0.o: in function `_mjit0':
_ruby_mjit_p17511u0.c:(.text+0x46c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17511u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p17511u1.o: in function `_mjit1':
_ruby_mjit_p17511u1.c:(.text+0x46c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17511u1.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p17511u2.o: in function `_mjit2':
_ruby_mjit_p17511u2.c:(.text+0x46c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17511u2.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p17511u3.o: in function `_mjit3':
_ruby_mjit_p17511u3.c:(.text+0x46c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17511u3.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p17511u4.o: in function `_mjit4':
_ruby_mjit_p17511u4.c:(.text+0x46c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17511u4.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p17511u5.o: in function `_mjit5':
_ruby_mjit_p17511u5.c:(.text+0x46c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17511u5.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p17511u6.o: in function `_mjit6':
_ruby_mjit_p17511u6.c:(.text+0x46c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17511u6.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p17511u7.o: in function `_mjit7':
_ruby_mjit_p17511u7.c:(.text+0x46c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17511u7.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p17511u8.o: in function `_mjit8':
_ruby_mjit_p17511u8.c:(.text+0x46c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17511u8.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p17511u9.o: in function `_mjit9':
_ruby_mjit_p17511u9.c:(.text+0x46c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17511u9.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p17511u10.o: in function `_mjit10':
_ruby_mjit_p17511u10.c:(.text+0x490): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17511u10.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<11> expected but was
<0>.

 56) Failure:
TestJIT#test_program_counter_with_regexpmatch [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:965]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""

2.times do
  break if /a/ =~ "ab" && !$~[0]
  print $~[0]
end

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p17646u0.o: in function `_mjit0':
_ruby_mjit_p17646u0.c:(.text+0xcd4): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17646u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 57) Failure:
TestJIT#test_pushed_values_with_opt_aref_with [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:984]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""

2.times do
  p(Thread.current["a"])
end

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p17704u0.o: in function `vm_sendish.constprop.15':
_ruby_mjit_p17704u0.c:(.text+0x5a8): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17704u0.o: in function `_mjit0':
_ruby_mjit_p17704u0.c:(.text+0xe10): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17704u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 58) Failure:
TestJIT#test_pushed_values_with_opt_aset_with [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:975]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""

2.times do
  print(Thread.current["a"] = {})
end

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p17775u0.o: in function `vm_sendish.constprop.15':
_ruby_mjit_p17775u0.c:(.text+0x5a8): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17775u0.o: in function `_mjit0':
_ruby_mjit_p17775u0.c:(.text+0xe44): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17775u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 59) Failure:
TestJIT#test_stack_pointer_with_assignment [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:926]:
Expected 1 times of JIT success, but succeeded 0 times.

script:
"""

2.times do
  a, _ = nil
  p a
end

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p17828u0.o: in function `_mjit0':
_ruby_mjit_p17828u0.c:(.text+0x600): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p17828u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<1> expected but was
<0>.

 60) Failure:
TestJIT#test_unload_units_and_compaction [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:686]:
stdout:
"""
012345678910
"""

stderr:
"""
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u0.o: in function `_mjit0':
_ruby_mjit_p17903u0.c:(.text+0x480): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u1.o: in function `_mjit1':
_ruby_mjit_p17903u1.c:(.text+0x480): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u1.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u2.o: in function `_mjit2':
_ruby_mjit_p17903u2.c:(.text+0x480): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u2.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u3.o: in function `_mjit3':
_ruby_mjit_p17903u3.c:(.text+0x480): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u3.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u4.o: in function `_mjit4':
_ruby_mjit_p17903u4.c:(.text+0x480): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u4.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u5.o: in function `_mjit5':
_ruby_mjit_p17903u5.c:(.text+0x480): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u5.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u6.o: in function `_mjit6':
_ruby_mjit_p17903u6.c:(.text+0x480): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u6.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u7.o: in function `_mjit7':
_ruby_mjit_p17903u7.c:(.text+0x480): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u7.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u8.o: in function `_mjit8':
_ruby_mjit_p17903u8.c:(.text+0x480): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u8.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u9.o: in function `_mjit9':
_ruby_mjit_p17903u9.c:(.text+0x480): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u9.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u10.o: in function `_mjit10':
_ruby_mjit_p17903u10.c:(.text+0x480): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u10.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
JIT success (198.6ms): block in <main>@-e:16 -> /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p18078u11.c
Successful MJIT finish
Successful MJIT finish
"""
.
Expected /\AJIT success \(\d+\.\dms\): mjit0@\(eval\):/ to match "/usr/bin/ld: /tmp/jit_test_unload_units_20201113-4600-xj2dl9/_ruby_mjit_p17903u0.o: in function `_mjit0':\n".

 61) Failure:
TestJIT#test_unload_units_on_fiber [/usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_jit.rb:636]:
Expected 12 times of JIT success, but succeeded 0 times.

script:
"""

def a1() a2(false); a2(true) end
def a2(a) a3(a) end
def a3(a) a4(a) end
def a4(a) a5(a) end
def a5(a) a6(a) end
def a6(a) a7(a) end
def a7(a) a8(a) end
def a8(a) a9(a) end
def a9(a) a10(a) end
def a10(a)
  if a
    Fiber.new { a11 }.resume
  end
end
def a11() print('hello') end
a1

"""


stderr:
"""
/usr/bin/ld: /tmp/_ruby_mjit_p18087u0.o: in function `vm_sendish.constprop.5':
_ruby_mjit_p18087u0.c:(.text+0x3f0): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p18087u0.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p18087u1.o: in function `_mjit1':
_ruby_mjit_p18087u1.c:(.text+0x488): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p18087u1.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p18087u2.o: in function `_mjit2':
_ruby_mjit_p18087u2.c:(.text+0x488): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p18087u2.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p18087u3.o: in function `_mjit3':
_ruby_mjit_p18087u3.c:(.text+0x488): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p18087u3.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p18087u4.o: in function `_mjit4':
_ruby_mjit_p18087u4.c:(.text+0x488): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p18087u4.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p18087u5.o: in function `_mjit5':
_ruby_mjit_p18087u5.c:(.text+0x488): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p18087u5.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p18087u6.o: in function `_mjit6':
_ruby_mjit_p18087u6.c:(.text+0x488): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p18087u6.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p18087u7.o: in function `_mjit7':
_ruby_mjit_p18087u7.c:(.text+0x488): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p18087u7.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p18087u8.o: in function `_mjit8':
_ruby_mjit_p18087u8.c:(.text+0x488): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p18087u8.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p18087u9.o: in function `vm_sendish.constprop.23':
_ruby_mjit_p18087u9.c:(.text+0x5cc): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p18087u9.o: in function `method_missing.constprop.24':
_ruby_mjit_p18087u9.c:(.text+0x8e0): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p18087u9.o: in function `refine_sym_proc_call':
_ruby_mjit_p18087u9.c:(.text+0xc38): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p18087u9.o: in function `_mjit9':
_ruby_mjit_p18087u9.c:(.text+0x17b0): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p18087u9.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p18087u10.o: in function `_mjit10':
_ruby_mjit_p18087u10.c:(.text+0x46c): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p18087u10.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /tmp/_ruby_mjit_p18087u11.o: in function `_mjit11':
_ruby_mjit_p18087u11.c:(.text+0x490): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: /tmp/_ruby_mjit_p18087u11.so: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
Successful MJIT finish

"""

.
<12> expected but was
<0>.

 62) Error:
TestIO_Console#test_set_winsize_console:
Errno::EINVAL: Invalid argument
    /usr/ports/opt/ruby/work/src/ruby-2.7.2/test/io/console/test_io_console.rb:432:in `winsize='
    /usr/ports/opt/ruby/work/src/ruby-2.7.2/test/io/console/test_io_console.rb:432:in `test_set_winsize_console'

 63) Error:
TestRefinement#test_prepend_after_refine_wb_miss:
Timeout::Error: execution of assert_normal_exit expired timeout (30 sec)
pid 24744 exit 1
| -:38:in `block in <main>': NameError
| 	from -:3:in `times'
| 	from -:3:in `<main>'
| 

    /usr/ports/opt/ruby/work/src/ruby-2.7.2/test/ruby/test_refinement.rb:913:in `test_prepend_after_refine_wb_miss'

Finished tests in 4778.904621s, 4.4108 tests/s, 569.7280 assertions/s.
21079 tests, 2722676 assertions, 61 failures, 2 errors, 80 skips

ruby -v: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [powerpc-linux]
make: *** [uncommon.mk:782: yes-test-all] Error 63
